### ISSUE TITLE
Circuit AI places three mexes on one spot

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#106]
See https://github.com/ZeroK-RTS/Zero-K/issues/3824

**Comment by rlcevg** [comment]
https://github.com/ZeroK-RTS/Zero-K/issues/2032
Assumption:
1) some cases were solved by Lua, but not all and engine still allows it.
2) Engine IsPossibleToBuildAt() returns true.
3) UnitIdle (builder) and UnitFinished (mex) events were never sent for AI.

Issue will take some time as i can't watch replay at the moment without opengl-3 capable working video at dev-PC.

**Comment by rlcevg** [comment]
[20200310_031419_TitanDuel 2_104.0.1-1435-g79d77ca maintenance.zip](https://github.com/ZeroK-RTS/Zero-K/files/4310807/20200310_031419_TitanDuel.2_104.0.1-1435-g79d77ca.maintenance.zip) chronology:
[f=0016794] CBuilderCAI::GiveCommandReal for unitId=13702 - **staticmex** order at (808, 4456)
[f=0016802] CBuilderCAI::GiveCommandReal for unitId=22445 - **staticmex** order at (808, 4456)
[f=0017289] UnitCreated: id=8340 | defId=530 | x=808, z=4456 | builder=22445 - **staticmex** created
[f=0017289] CBuilderCAI::GiveCommandReal for unitId=13702 - **staticmex** order at (808, 4456)
`CBuilderCAI::IsBuildPosBlocked == false` instead of **true** as
`const CSolidObject* s = groundBlockingObjectMap.GroundBlocked(bi.pos);`
returns _movable_ **cloakraid** instead of already created in this very frame **staticmex**
[f=0017289] UnitCreated: id=28956 | defId=530 | x=808, z=4456 | builder=13702 - **staticmex** created
[f=0017289] CBuilderCAI::GiveCommandReal for unitId=22445 - **staticmex** order at (808, 4456)
same story again with `CBuilderCAI::IsBuildPosBlocked == false`: instead of **staticmex**-nanoframe function tests _movable_ **cloakraid**
[f=0017289] UnitCreated: id=10411 | defId=530 | x=808, z=4456 | builder=22445 - **staticmex** created

Too many actions for a single frame.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/a1374fc94d73be83160d5601b7df35d08df852c5

**Comment by sprunk** [comment]
NB https://github.com/spring/spring/commit/4a97df4f98c3d9afcd9b21d4062e91d96b3a4da8

**Comment by rlcevg** [comment]
well, this one is the case of allyteam == cu->allyteam (own glaive was standing at build position), so i guess not related
