### ISSUE TITLE
[BAR] Do not build in player bases

### ISSUE THREAD

**Issue by sprunk** [rlcevg/CircuitAI#132]
See https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2620

Sounds like it would be best as a config value. ZK is not about making a simcity so we don't mind that much if Circuit helps players out but maybe we would use it for singleplayer as well.

**Comment by rlcevg** [comment]
Forbidden area will be a square around **factory** with default size of a side such as
BAR: 128*9=1152 elmos.
ZK: 0 elmos.

For BAR it could include an AIOption.lua entry with ON/OFF value. When ON it could use AngelScript to define the size of the area: calculated from the size of the map, the name, or the distance between mex clusters; multiples of 128, truncated otherwise.
For ZK it could be an AIOption.lua with `float` value as a _half_-side of a square (may change to radius in the future, hence _half_), multiples of 128, truncated otherwise.

**Comment by rlcevg** [comment]
BAR: https://github.com/rlcevg/CircuitAI/commit/90981974b64c9dc34190e0e1276cb5f2a91f1211
ZK: https://github.com/rlcevg/CircuitAI/commit/ea8ad431afc8ea5208aac21d3063ead9fc54de7c

ZK caveat: pylons linking/gridding ignore ally zones.
