### ISSUE TITLE
Circuit AI limited units issue

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#35]
A circuit AI with these units unlocked plops a factory and never builds anything with it:
- "factorycloak",
- "corllt",
- "cormex",
- "armsolar",
- "armwar",

**Comment by rlcevg** [comment]
Due to [config limitation](https://github.com/rlcevg/CircuitAI/blob/83eb7ea3ccd1bf96137b734b1248b4ad9a819036/data/config/circuit.json#L32) armwar has 0 probability to be built.
The possible workaround is to allow [units with 0 probability if total magnitude is also 0](https://github.com/rlcevg/CircuitAI/blob/83eb7ea3ccd1bf96137b734b1248b4ad9a819036/src/circuit/module/FactoryManager.cpp#L626):
```
-    if (dice < total) {
+    if (dice <= total) {
```
But the right way to do is to provide proper config (with only unlocked units). I'll work on example (providing config through **json** AIOption).

**Comment by GoogleFrog** [comment]
I would like the workaround which builds something at random if all probabilities are zero because it is the most common usecase. I have experimented with writing circuit configs with lua and it is a big mess. Also, there are modoptions to disable units so this could come up in a skirmish game.

**Comment by rlcevg** [comment]
I'll add such workaround.
But issue with current armwar example is something to keep in mind. armwar has **support** tag in default config - it will only defend own expansion and group up until some attacker/assault appears (alas they're all disabled), therefore it will never launch attack with armwar units only.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/b4b31269f94c06b58fa7940b4f6cf629b93a6017
https://github.com/rlcevg/CircuitAI/commit/f874a90dbb93f06033f0a5181a7529be96e736cb
