### ISSUE TITLE
Some circuit orders have massive Y on Mini Super Speed Metal Wide

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#97]
![image](https://user-images.githubusercontent.com/1318249/54484837-08342080-48c2-11e9-9b4b-4da95f2bcbd3.png)

Note that this map crashes with stable ZK.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/54484880-ff901a00-48c2-11e9-97d4-134e3e3c31b6.png)

**Comment by rlcevg** [comment]
I thought leaving metal income in pos.y for the spot was harmless, plus i hoped no one will dare to play vs AI on a metal-area map, because of how quickly AI creates lag-fests with unlimited income :)

Just for the clarity: proper support of metal-area maps was not finished. Current method uses engine's Map::GetResourceMapSpotsPositions that returns at most 10000 discrete spots (that may not cover whole area), then AI selects small random portion (8x8: ~80; 24x24: ~240 spots) of those spots and plays as if it was casual map. GetResourceMapSpotsPositions returns income inside pos.y, but i guess getting actual height with Map::GetElevationAt or Map::GetHeightMap won't hurt much.

As for the crash - will try to reproduce.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/c73fdcb7a03361d7c361636a45accd3597ea600b
